"""
Agent 6 — PR Opener
Responsibility: Commit changes to a new branch and open a GitHub Pull Request.
"""
import logging
import os
import subprocess
from datetime import datetime
from github import Github
from core.state  import AgentState, AgentStatus
from core.config import cfg

logger = logging.getLogger(__name__)


def _git(cmd: list[str], cwd: str) -> str:
    """Run a git command and return stdout."""
    result = subprocess.run(
        ["git"] + cmd,
        cwd=cwd,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"git {' '.join(cmd)} failed:\n{result.stderr}")
    return result.stdout.strip()


def _create_branch_and_push(repo_path: str, branch_name: str, issue_number: int) -> None:
    # Configure git identity (needed in CI / fresh environments)
    _git(["config", "user.email", "ai-agent@github-actions.bot"], cwd=repo_path)
    _git(["config", "user.name",  "AI Agent"], cwd=repo_path)

    # Create and checkout new branch
    _git(["checkout", "-b", branch_name], cwd=repo_path)

    # Stage all changes
    _git(["add", "-A"], cwd=repo_path)

    # Commit
    _git(
        ["commit", "-m", f"fix: auto-fix for issue #{issue_number}\n\n[AI-generated] See PR for details"],
        cwd=repo_path,
    )

    # Push — assumes remote is already set (clone sets it up)
    _git(["push", "origin", branch_name], cwd=repo_path)
    logger.info("Branch %s pushed to origin", branch_name)


def _build_pr_body(state: AgentState) -> str:
    test_result = state.get("test_result", {})
    passed_icon = "✅" if test_result.get("passed") else "⚠️"

    messages_md = ""
    for m in state.get("messages", []):
        agent   = m.get("agent", "?")
        summary = m.get("summary", "")
        messages_md += f"- **{agent}**: {summary}\n"

    return f"""## 🤖 AI-Generated Fix for Issue #{state['issue_number']}

> **{state['issue_title']}**

---

### 📋 Plan

{state.get('plan', '_No plan available_')}

---

### 📁 Changed Files

{chr(10).join(f"- `{p['path']}`" for p in state.get('patched_files', []))}

---

### 🧪 Test Results

{passed_icon} Tests {'passed' if test_result.get('passed') else 'failed / not run'}

<details>
<summary>Test output</summary>

```
{test_result.get('output', 'N/A')[-3000:]}
```

</details>

---

### 🔍 Agent Execution Log

{messages_md}

---

*Generated by GitHub AI Agent • {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*
*Retries: {state.get('retry_count', 0)} / {state.get('max_retries', 3)}*
"""


def pr_opener_agent(state: AgentState) -> AgentState:
    logger.info("▶ pr_opener_agent: issue #%d", state["issue_number"])
    state["current_agent"] = "pr_opener"
    state["status"]        = AgentStatus.RUNNING

    try:
        issue_number = state["issue_number"]
        repo_name    = state["repo_name"]
        repo_path    = state["repo_local_path"]

        # Create unique branch name
        ts          = datetime.utcnow().strftime("%Y%m%d-%H%M%S")
        branch_name = f"ai-fix/issue-{issue_number}-{ts}"
        state["branch_name"] = branch_name

        # Push branch
        _create_branch_and_push(repo_path, branch_name, issue_number)

        # Open PR via GitHub API
        gh   = Github(cfg.github_token)
        repo = gh.get_repo(repo_name)
        issue_obj = repo.get_issue(issue_number)

        pr = repo.create_pull(
            title  = f"fix: {state['issue_title']} (AI fix for #{issue_number})",
            body   = _build_pr_body(state),
            head   = branch_name,
            base   = repo.default_branch,
        )

        # Link PR to issue
        issue_obj.create_comment(
            f"🤖 An automated PR has been opened to address this issue: {pr.html_url}"
        )

        state["pr_url"]    = pr.html_url
        state["pr_number"] = pr.number
        state["status"]    = AgentStatus.SUCCESS

        state["messages"].append({
            "agent":   "pr_opener",
            "summary": f"PR #{pr.number} opened",
            "pr_url":  pr.html_url,
        })

        logger.info("✅ PR opened: %s", pr.html_url)

    except Exception as exc:
        logger.exception("pr_opener_agent failed")
        state["errors"].append(f"pr_opener: {exc}")
        state["status"] = AgentStatus.FAILED

    return state
